<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="293341" started-at="2021-06-17T09:35:01Z" finished-at="2021-06-17T09:39:55Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="293341" started-at="2021-06-17T09:35:01Z" finished-at="2021-06-17T09:39:55Z">
      <class name="crmframework.crmAutomation.CAB256PageTest">
        <test-method status="PASS" signature="initialize()[pri:0, instance:crmframework.crmAutomation.CAB256PageTest@5e5792a0]" name="initialize" is-config="true" duration-ms="112850" started-at="2021-06-17T15:05:01Z" finished-at="2021-06-17T15:06:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="TS017_VerifyStatusReasonAtContactAndAccount()[pri:0, instance:crmframework.crmAutomation.CAB256PageTest@5e5792a0]" name="TS017_VerifyStatusReasonAtContactAndAccount" duration-ms="180295" started-at="2021-06-17T15:06:54Z" finished-at="2021-06-17T15:09:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Out of Business] but found [Active]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Out of Business] but found [Active]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at crmframework.crmAutomation.CAB256PageTest.TS017_VerifyStatusReasonAtContactAndAccount(CAB256PageTest.java:1055)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TS017_VerifyStatusReasonAtContactAndAccount -->
      </class> <!-- crmframework.crmAutomation.CAB256PageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
